
export const FETCH_SEARCH_BOOK_SUCCESS = 'FETCH_SEARCH_BOOK_SUCCESS';
export const FETCH_SEARCH_BOOK_INIT = 'FETCH_SEARCH_BOOK_INIT';

export const FETCH_BOOK_ID_INIT = 'FETCH_BOOK_ID_INIT';
export const FETCH_BOOK_ID_SUCCESS = 'FETCH_BOOK_ID_SUCCESS';


export const FETCH_USER_BOOK_SUCCESS = 'FETCH_USER_BOOK_SUCCESS';
export const FETCH_USER_BOOK_FAIL = 'FETCH_USER_BOOK_FAIL';
export const FETCH_USER_BOOK_INIT = 'FETCH_USER_BOOK_INIT';




