
export const FETCH_SEARCH_BOOK_SUCCESS = 'FETCH_SEARCH_BOOK_SUCCESS';
export const FETCH_SEARCH_BOOK_INIT = 'FETCH_SEARCH_BOOK_INIT';


export const FETCH_USER_BOOKINGS_SUCCESS = 'FETCH_USER_BOOKINGS_SUCCESS';
export const FETCH_USER_BOOKINGS_FAIL = 'FETCH_USER_BOOKINGS_FAIL';
export const FETCH_USER_BOOKINGS_INIT = 'FETCH_USER_BOOKINGS_INIT';


export const FETCH_RENTALS_INIT = 'FETCH_RENTALS_INIT';
export const FETCH_RENTALS_FAIL = 'FETCH_RENTALS_FAIL';


